[package]
name = "mirage-ui-host"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish = false

[[bin]]
name = "mirage-ui"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
getrandom.workspace = true
futures-executor.workspace = true
mirage-backend-drive.workspace = true
mirage-ipc.workspace = true
mirage-types.workspace = true
serde_json.workspace = true

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61", features = ["Win32_Foundation", "Win32_Security", "Win32_Storage_FileSystem", "Win32_UI_Shell", "Win32_UI_WindowsAndMessaging"] }
