[package]
name = "mirage-simulator"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
mirage-types.workspace = true
mirage-predictor.workspace = true
mirage-cache.workspace = true
serde.workspace = true
serde_json.workspace = true
