[package]
name = "mirage-fuzz"
version = "0.0.0"
edition = "2024"
publish = false

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
mirage-manifest = { path = "../crates/mirage-manifest" }
mirage-index = { path = "../crates/mirage-index" }
mirage-pack = { path = "../crates/mirage-pack" }
mirage-ipc = { path = "../crates/mirage-ipc" }

[[bin]]
name = "manifest"
path = "fuzz_targets/manifest.rs"
test = false
doc = false
bench = false
[[bin]]
name = "commit"
path = "fuzz_targets/commit.rs"
test = false
doc = false
bench = false
[[bin]]
name = "midx"
path = "fuzz_targets/midx.rs"
test = false
doc = false
bench = false
[[bin]]
name = "pack_frame"
path = "fuzz_targets/pack_frame.rs"
test = false
doc = false
bench = false
[[bin]]
name = "ipc_frame"
path = "fuzz_targets/ipc_frame.rs"
test = false
doc = false
bench = false
[[bin]]
name = "windows_path"
path = "fuzz_targets/windows_path.rs"
test = false
doc = false
bench = false
