import { createElement as h } from 'react';
import { ArrowUpRight, ArrowRight, HardDrives, FolderSimple, FileText, Cloud, Check, GithubLogo, ShieldCheck, Code, CaretDown, Plus } from '@phosphor-icons/react';

const repo = 'https://github.com/dantwoashim/MirageSSD';
const origin = 'https://miragessd.prabinghimire1.com.np';
const icon = (Icon, size = 20, className = '') => h(Icon, { size, weight: 'regular', className, 'aria-hidden': true });
const a = (href, text, className = '') => h('a', { href, className }, text);
const note = (text) => h('p', { className: 'eyebrow' }, text);
const para = (text, className = '') => h('p', { className: `text-muted leading-relaxed ${className}` }, text);
const cta = (href, text, secondary = false) => a(href, [h('span', { key: 'text' }, text), h(ArrowUpRight, { key: 'icon', size: 18, 'aria-hidden': true })], secondary ? 'button secondary' : 'button');
const textLink = (href, text) => a(href, [h('span', { key: 'text' }, text), h(ArrowUpRight, { key: 'icon', size: 16, 'aria-hidden': true })], 'text-link');
function Brand() {
  return a('/', [h('span', { key: 'mark', className: 'brand-mark', 'aria-hidden': true }, h('i'), h('i'), h('i')), h('span', { key: 'word' }, 'Mirage', h('span', { className: 'font-normal text-muted' }, 'SSD'))], 'inline-flex items-center gap-3 text-[21px] font-semibold tracking-tight');
}

export function Layout({ title, description, path, children }) {
  return h('html', { lang: 'en' },
    h('head', null, h('meta', { charSet: 'utf-8' }), h('meta', { name: 'viewport', content: 'width=device-width, initial-scale=1' }),
      h('title', null, title), h('meta', { name: 'description', content: description }),
      h('meta', { name: 'theme-color', content: '#f8f9f7' }), h('link', { rel: 'icon', href: '/favicon.svg', type: 'image/svg+xml' }),
      h('link', { rel: 'preload', href: '/geist-latin.woff2', as: 'font', type: 'font/woff2', crossOrigin: 'anonymous' }),
      h('link', { rel: 'canonical', href: `${origin}${path}` }), h('link', { rel: 'stylesheet', href: '/site.css' }),
      h('meta', { property: 'og:title', content: title }), h('meta', { property: 'og:description', content: description }),
      h('meta', { property: 'og:type', content: 'website' }), h('meta', { property: 'og:url', content: `${origin}${path}` })),
    h('body', null,
      a('#main', 'Skip to content', 'sr-only focus:not-sr-only focus:block focus:p-4'),
      h('header', { className: 'border-b border-line bg-paper' }, h('div', { className: 'shell flex min-h-21 flex-wrap items-center justify-between gap-4 py-4' }, h(Brand),
        h('nav', { 'aria-label': 'Main navigation', className: 'flex items-center gap-5 text-sm sm:gap-8' }, a('/#how-it-works', 'How it works', 'hidden text-muted hover:text-ink sm:block'), a('/#trust', 'Trust & privacy', 'hidden text-muted hover:text-ink md:block'), a(`${repo}/blob/main/docs/building.md`, 'Docs', 'text-muted hover:text-ink'), a(repo, [h(GithubLogo, { key: 'icon', size: 18, 'aria-hidden': true }), h('span', { key: 'label' }, 'GitHub')], 'inline-flex items-center gap-2 rounded-lg border border-line bg-white px-4 py-2 hover:border-leaf')))),
      h('main', { id: 'main' }, children),
      h('footer', { className: 'border-t border-line' }, h('div', { className: 'shell grid gap-10 py-12 md:grid-cols-[1.8fr_1fr_1fr]' },
        h('div', { className: 'space-y-4' }, h(Brand), para('Cloud storage. Local familiarity.', 'text-sm'), h('p', { className: 'max-w-sm text-xs leading-relaxed text-muted' }, 'Independent, open-source software. Not affiliated with or endorsed by Google or Microsoft.')),
        h('div', null, h('p', { className: 'mb-4 text-sm font-medium' }, 'Project'), h('nav', { 'aria-label': 'Project resources', className: 'flex flex-col items-start gap-3 text-sm text-muted' }, a(repo, 'Source code'), a(`${repo}/blob/main/docs/building.md`, 'Installation guide'), a(`${repo}/issues`, 'Support & issues'), a(`${repo}/actions`, 'Build checks'))),
        h('div', null, h('p', { className: 'mb-4 text-sm font-medium' }, 'Your information'), h('nav', { 'aria-label': 'Legal', className: 'flex flex-col items-start gap-3 text-sm text-muted' }, a('/privacy', 'Privacy policy'), a('/terms', 'Terms of use'), a('https://myaccount.google.com/connections', 'Manage Google access')))),
        h('div', { className: 'shell flex flex-wrap justify-between gap-3 border-t border-line py-6 text-xs text-muted' }, h('p', null, '© 2026 MirageSSD contributors'), a(`${repo}/blob/main/LICENSE`, 'Source licensed under Apache-2.0')))));
}

function Explorer() {
  return h('figure', { className: 'relative min-w-0' },
    h('div', { className: 'explorer-scene' },
      h('div', { className: 'explorer-window' },
        h('div', { className: 'flex items-center justify-between border-b border-line px-5 py-4 text-xs text-muted' }, h('span', { className: 'flex items-center gap-2 font-medium text-ink' }, icon(HardDrives, 17), 'MirageSSD'), h('span', { className: 'font-mono tracking-[.4em]', 'aria-hidden': true }, '− □ ×')),
        h('div', { className: 'flex items-center gap-3 border-b border-line px-5 py-3 text-xs' }, icon(ArrowRight, 14, 'rotate-180 text-muted'), h('span', { className: 'flex min-w-0 flex-1 items-center gap-2 rounded-md border border-line bg-paper px-3 py-2 text-muted' }, 'This PC', icon(CaretDown, 10, '-rotate-90'), h('span', { className: 'truncate text-ink' }, 'MirageSSD (M:)'))),
        h('div', { className: 'grid min-h-65 grid-cols-[100px_minmax(0,1fr)] sm:grid-cols-[120px_minmax(0,1fr)]' },
          h('div', { className: 'space-y-4 border-r border-line bg-paper/60 px-3 py-5 text-[11px] text-muted' }, h('p', null, 'Quick access'), h('p', null, 'Desktop'), h('p', null, 'Downloads'), h('p', { className: 'pt-3' }, 'This PC'), h('p', { className: '-mx-1 rounded bg-leaf/10 px-2 py-2 font-medium text-leaf' }, 'MirageSSD')),
          h('div', { className: 'min-w-0 px-4 py-5 sm:px-5' }, h('div', { className: 'mb-4 flex items-center justify-between border-b border-line pb-3 text-[10px] text-muted' }, h('span', null, 'Name'), h('span', null, 'Availability')),
            ...[[FolderSimple, 'Documents', 'On Drive'], [FolderSimple, 'Photo archive', 'On Drive'], [FolderSimple, 'Projects', 'Cached'], [FileText, 'Readme.txt', 'Cached']].map(([Icon, name, state]) => h('div', { key: name, className: 'flex items-center justify-between gap-2 py-3 text-xs' }, h('span', { className: 'flex min-w-0 items-center gap-2' }, icon(Icon, 20, 'shrink-0 text-leaf'), h('span', { className: 'truncate' }, name)), icon(state === 'Cached' ? Check : Cloud, 15, 'shrink-0 text-muted'))))),
        h('div', { className: 'flex justify-between border-t border-line px-5 py-3 text-[10px] text-muted' }, h('span', null, '4 illustrative items'), h('span', null, 'App-authorized storage'))),
      h('div', { className: 'cache-label' }, icon(HardDrives, 22, 'text-leaf'), h('div', null, h('p', { className: 'text-xs font-semibold' }, 'Local write-back cache'), h('p', { className: 'mt-1 text-[11px] text-muted' }, 'Stage here. Upload in the background.')))),
    h('figcaption', { className: 'mt-4 text-center text-[11px] text-muted' }, 'Illustrative view of the workflow, not a live status screen.'));
}

function Heading({ label, title, text }) {
  return h('div', { className: 'mb-10 max-w-2xl space-y-4' }, note(label), h('h2', { className: 'text-3xl font-medium leading-tight tracking-tight sm:text-[40px]' }, title), text && para(text));
}

export function Home() {
  return h('div', null,
    h('section', { className: 'shell grid items-center gap-10 py-14 lg:grid-cols-[1fr_1.12fr] lg:gap-14 lg:py-22' },
      h('div', { className: 'space-y-7' }, h('div', { className: 'inline-flex items-center gap-2 rounded-full border border-line bg-white px-3 py-1.5 text-[11px] font-medium' }, h('span', { className: 'h-1.5 w-1.5 rounded-full bg-leaf' }), 'WINDOWS 11', h('span', { className: 'text-muted' }, '/ ENGINEERING PREVIEW')),
        h('h1', { className: 'max-w-lg text-[46px] font-medium leading-[1.05] tracking-[-.055em] sm:text-[64px] lg:text-[68px]' }, 'More room.', h('br'), h('span', { className: 'text-muted' }, 'Same Explorer.')),
        para('Put your Google Drive storage within reach of the apps you already use. Read, write, and organize files through a familiar Windows drive—with a local cache doing the everyday work.', 'max-w-[440px] text-[17px]'),
        h('div', { className: 'flex flex-wrap gap-3 pt-1' }, cta('#get-started', 'Start with the preview'), cta(repo, 'Explore the source', true)),
        h('p', { className: 'flex flex-wrap items-center gap-x-4 gap-y-2 text-xs text-muted' }, h('span', { className: 'inline-flex items-center gap-1.5' }, icon(Code, 15), 'Open source'), h('span', null, 'No storage subscription from us'))), h(Explorer)),
    h('div', { className: 'border-y border-line bg-white/70' }, h('div', { className: 'shell flex flex-wrap items-center justify-between gap-x-8 gap-y-4 py-6 text-xs text-muted' }, h('span', { className: 'text-[10px] font-medium uppercase tracking-[.16em]' }, 'Built on established tools'), h('span', { className: 'font-medium text-ink' }, 'Google Drive API'), h('span', { className: 'font-medium text-ink' }, 'rclone + WinFsp'), h('span', { className: 'font-medium text-ink' }, 'Rust'), a(`${repo}/blob/main/LICENSE`, 'Apache-2.0 source', 'underline underline-offset-4'))),
    h('section', { id: 'how-it-works', className: 'shell py-18 sm:py-24' }, h(Heading, { label: '01 / THE EVERYDAY WORKFLOW', title: 'A drive letter. Not another place to work.', text: 'Keep the file operations you know. MirageSSD handles the connection between a local cache and app-authorized storage in your Google account.' }),
      h('div', { className: 'grid gap-10 md:grid-cols-2 md:gap-20' },
        h('div', { className: 'space-y-8' }, ...[[FolderSimple, 'Work from Explorer', 'Open files, save downloads, and copy folders using ordinary filesystem paths. Setup prefers M: or chooses an available drive letter.'], [HardDrives, 'Keep useful data nearby', 'Recently used content stays in a local cache. Writes are staged on your PC before upload, so every operation does not need to wait for the network.']].map(([Icon, title, text]) => h('div', { key: title, className: 'flex gap-4' }, icon(Icon, 25, 'mt-1 shrink-0 text-leaf'), h('div', { className: 'space-y-3' }, h('h3', { className: 'text-lg font-medium' }, title), para(text, 'text-sm'))))),
        h('div', { className: 'rounded-2xl border border-line bg-white px-6 py-7 sm:px-8' }, note('WHAT HAPPENS TO A WRITE'),
          ...[['01', 'Save to the mounted drive', 'Your file is staged in local storage.'], ['02', 'Upload to Google Drive', 'Background transfers use your connection.'], ['03', 'Verify before removing originals', 'A finished local copy is not proof of a finished upload.']].map(([n, title, text]) => h('div', { key: n, className: 'mt-6 flex gap-4' }, h('span', { className: 'font-mono text-xs text-leaf' }, n), h('div', null, h('h3', { className: 'text-sm font-medium' }, title), para(text, 'mt-1 text-xs'))))))),
    h('section', { className: 'border-y border-line bg-white' }, h('div', { className: 'shell grid gap-12 py-18 md:grid-cols-[1fr_1.2fr] md:gap-20 sm:py-24' },
      h('div', { className: 'space-y-5' }, note('02 / PERFORMANCE, EXPLAINED'), h('h2', { className: 'text-3xl font-medium leading-tight tracking-tight sm:text-[40px]' }, 'Local when cached.', h('br'), 'Network when needed.'), para('A cache makes repeat access more responsive. It does not turn an internet connection into an SSD.'), textLink(`${repo}/blob/main/docs/architecture.md`, 'Read the architecture')),
      h('div', null, ...[['Cached reads', 'Local disk and Windows memory cache'], ['New writes', 'Local staging space, then background upload'], ['Uncached reads', 'Internet speed, latency, and Google Drive'], ['Large folder transfers', 'Upload bandwidth and per-file overhead']].map(([name, value]) => h('div', { key: name, className: 'grid gap-2 border-b border-line py-5 first:pt-0 sm:grid-cols-[140px_1fr]' }, h('h3', { className: 'text-sm font-medium' }, name), para(value, 'text-sm'))), h('p', { className: 'mt-6 text-xs leading-relaxed text-muted' }, 'Cache space is real local disk space. Open files and pending uploads cannot safely be evicted; downloads can fill the disk if uploads cannot keep up.')))),
    h('section', { id: 'trust', className: 'shell py-18 sm:py-24' }, h('div', { className: 'grid gap-10 md:grid-cols-[1.1fr_1fr] md:gap-20' },
      h('div', { className: 'space-y-6' }, note('03 / TRUST IS SOMETHING YOU CAN CHECK'), h('h2', { className: 'text-3xl font-medium leading-tight tracking-tight sm:text-[40px]' }, 'Your account.', h('br'), 'A permission you can inspect.'), para('Google handles sign-in in your system browser. MirageSSD requests drive.file, not unrestricted access to every file in My Drive.'), para('Your file contents travel between your PC and Google Drive. This website is not a transfer proxy and does not receive your Drive tokens.'), textLink('/privacy', 'Read the full privacy policy')),
      h('div', { className: 'divide-y divide-line border-y border-line' }, ...[[Code, 'Inspect the implementation', 'Source, dependency notices, and architecture are public.', repo, 'View source'], [ShieldCheck, 'Review the build checks', 'Read the actual Windows, Linux, security, and fuzz workflow results.', `${repo}/actions`, 'Open GitHub Actions'], [GithubLogo, 'Talk to the maintainer', 'Report a problem or follow development in public. Never post tokens or private files.', `${repo}/issues`, 'Support & issues']].map(([Icon, title, text, href, label]) => h('div', { key: title, className: 'flex gap-4 py-6' }, icon(Icon, 22, 'mt-1 shrink-0 text-leaf'), h('div', { className: 'space-y-2' }, h('h3', { className: 'font-medium' }, title), para(text, 'text-sm'), textLink(href, label))))))),
    h('section', { id: 'get-started', className: 'bg-ink text-white' }, h('div', { className: 'shell grid gap-12 py-16 md:grid-cols-[1fr_1.1fr] md:gap-20 sm:py-20' },
      h('div', { className: 'space-y-6' }, h('p', { className: 'text-[10px] font-medium uppercase tracking-[.18em] text-white/65' }, '04 / START SMALL. VERIFY THE ROUND TRIP.'), h('h2', { className: 'text-3xl font-medium leading-tight tracking-tight sm:text-[40px]' }, 'Make room for', h('br'), 'a better file workflow.'), h('p', { className: 'max-w-md text-sm leading-relaxed text-white/70' }, 'Build from the public source or use a preview installer supplied by a maintainer. This site does not currently host an installer.'), a(`${repo}/blob/main/docs/building.md`, [h('span', { key: 'label' }, 'Open the installation guide'), h(ArrowUpRight, { key: 'icon', size: 18, 'aria-hidden': true })], 'button bg-white! text-ink! hover:bg-white/90!')),
      h('ol', { className: 'space-y-7' }, ...[['01', 'Check your PC', 'Windows 11 x64, internet, an NTFS volume with at least 12 GiB free, and permission to install WinFsp.'], ['02', 'Install and connect', 'Run a trusted preview installer and authorize your own Google account. Google sign-in is in production; no tester-email registration is needed. Organization account policies may still apply.'], ['03', 'Test with disposable files', 'Copy a small folder, wait for uploads, then verify it can be read back. Keep originals until you have verified a restore.']].map(([n, title, text]) => h('li', { key: n, className: 'flex gap-5' }, h('span', { className: 'pt-1 font-mono text-xs text-white/50' }, n), h('div', null, h('h3', { className: 'mb-2 font-medium' }, title), h('p', { className: 'text-sm leading-relaxed text-white/70' }, text))))))),
    h('section', { className: 'shell grid gap-8 py-18 md:grid-cols-[1fr_1.6fr] md:gap-20 sm:py-24' }, h('div', null, note('GOOD QUESTIONS'), h('h2', { className: 'mt-4 text-3xl font-medium tracking-tight' }, 'Before you connect.')),
      h('div', null, ...[
        ['Does MirageSSD give me extra Google storage?', 'No. It uses the quota of the Google account you connect. MirageSSD does not sell or increase your storage subscription.'],
        ['Can I see everything already in My Drive?', 'No. The drive.file scope limits access to app-authorized files. The preview mounts an application-owned folder, not a full mirror of your existing Drive.'],
        ['Are my files encrypted by MirageSSD?', 'Ordinary files on the writable drive are not client-side encrypted by MirageSSD. Transfers use HTTPS; local cached contents remain on your device. Separate encrypted repository and backup features are different paths.'],
        ['Can I use it as my only backup or run games on it?', 'No. This is an engineering preview, not a certified backup system or physical SSD replacement. Keep independent backups. Games, databases, and virtual machines should run on native storage.'],
        ['What happens when I uninstall?', 'The preview retains cache, credentials, local metadata, and cloud files to avoid unintended data loss. Stop the mount and revoke Google access to disconnect. See the privacy policy for deletion guidance.'],
        ['Is this ready for every desktop?', 'The current preview targets Windows 11 x64, with a macOS 12+ preview app that requires macFUSE. Linux desktop mounting, signed or notarized installers, and clean-machine certification are not delivered. Do not disable Windows security or Gatekeeper to run an unsigned preview.']
      ].map(([question, answer]) => h('details', { key: question, className: 'faq border-b border-line first:border-t' }, h('summary', { className: 'flex cursor-pointer list-none items-center justify-between gap-5 py-5 text-sm font-medium' }, question, icon(Plus, 18, 'shrink-0 transition-transform')), h('p', { className: 'pb-6 pr-6 text-sm leading-relaxed text-muted' }, answer))))));
}
