#include "mirage_ffi.h"
#include <winfsp/winfsp.h>
extern "C" NTSTATUS mirage_status_to_ntstatus(MirageStatus status){switch(status){case MIRAGE_OK:return STATUS_SUCCESS;case MIRAGE_INVALID_ARGUMENT:return STATUS_INVALID_PARAMETER;case MIRAGE_NOT_FOUND:return STATUS_OBJECT_NAME_NOT_FOUND;case MIRAGE_ACCESS_DENIED:return STATUS_ACCESS_DENIED;case MIRAGE_WOULD_BLOCK:return STATUS_PENDING;case MIRAGE_CANCELLED:return STATUS_CANCELLED;case MIRAGE_INTEGRITY_FAILURE:case MIRAGE_BACKEND_UNAVAILABLE:case MIRAGE_IO_ERROR:return STATUS_IO_DEVICE_ERROR;default:return STATUS_INTERNAL_ERROR;}}
